# Work section

projects:
- {name: Interview System, folder: 'work1'}
- {name: School Management System, folder: 'work2'}
- {name: Minimal B&W Design, folder: 'work3'}
# - {name: Profile Page, folder: 'work4'}
# - {name: Design, folder: 'work5'}
# - {name: Simply Elegant, folder: 'work6'}
